CREATE DATABASE product_db;

USE product_db;

CREATE TABLE users (
	id INTEGER(11) AUTO_INCREMENT NOT NULL,
	username VARCHAR(100) NOT NULL,
    password VARCHAR(255) NOT NULL,
    display_name VARCHAR(100) NOT NULL,
    state VARCHAR(100) NOT NULL DEFAULT "active",
	PRIMARY KEY(id)
);

CREATE TABLE topics (
	id INTEGER(11) AUTO_INCREMENT NOT NULL,
    topic_name VARCHAR(255) NOT NULL,
	user_id INTEGER(11) NOT NULL,
    position INTEGER(10) NOT NULL DEFAULT 1,
    creation_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    state VARCHAR(100) NOT NULL DEFAULT "active",
    PRIMARY KEY(id)
);

CREATE TABLE tasks (
	id INTEGER(11) AUTO_INCREMENT NOT NULL,
    task_title VARCHAR(255) NOT NULL,
    topic_id INTEGER(11) NOT NULL,
    default_position INTEGER(11) NOT NULL DEFAULT 1,
    priority VARCHAR(50),
    end_date DATETIME,
    creation_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    state VARCHAR(100) NOT NULL DEFAULT "active",
    PRIMARY KEY(id)
);

CREATE TABLE step_lists (
	id INTEGER(11) AUTO_INCREMENT NOT NULL,
    list_title VARCHAR (100),
    task_id INTEGER(11) NOT NULL,
	creation_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	state VARCHAR(100) NOT NULL DEFAULT "active",
	PRIMARY KEY(id)
);

CREATE TABLE steps (
	id INTEGER(11) AUTO_INCREMENT NOT NULL,
    list_id INTEGER(11) NOT NULL,
    position INTEGER(11) NOT NULL,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
	creation_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	state VARCHAR(100) NOT NULL DEFAULT "active",
    PRIMARY KEY(id)
);

CREATE TABLE audio_rec (
	id INTEGER(11) AUTO_INCREMENT NOT NULL,
    task_id INTEGER(11) NOT NULL,
    position INTEGER(11) NOT NULL,
    name VARCHAR(100) NOT NULL,
    file_data LONGBLOB NOT NULL,
	creation_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    state VARCHAR(100) NOT NULL DEFAULT "active",
	PRIMARY KEY(id)
);

CREATE TABLE audio_time (
	id INTEGER(11) AUTO_INCREMENT NOT NULL,
    rec_id INTEGER(11) NOT NULL,
    time_offset INTEGER(11) NOT NULL,
    summary VARCHAR(255),
    color_code CHAR(6) NOT NULL DEFAULT '34993A',
	creation_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    state VARCHAR(100) NOT NULL DEFAULT "active",
    PRIMARY KEY(id)
);